version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    depends_on:
      - redis

  redis:
    image: redis

volumes:
  logvolume01: {}

